import type {
  HttpStatusType,
  ExceptionCodeType,
  ExceptionIdentifierType,
} from "./types";

export const HttpStatus: Record<string, HttpStatusType> = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  INTERNAL_SERVER_ERROR: 500,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const ExceptionCode: Record<string, ExceptionCodeType> = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  DATA_INTEGRITY_ERROR: "DATA_INTEGRITY_ERROR",
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
  BUSINESS_LOGIC_ERROR: "BUSINESS_LOGIC_ERROR",
} as const;

export const ExceptionIdentifier: Record<string, ExceptionIdentifierType> = {
  USER_ERROR: "USER_ERROR",
  SYSTEM_ERROR: "SYSTEM_ERROR",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
  INPUT_ERROR: "INPUT_ERROR",
  RESOURCE_ERROR: "RESOURCE_ERROR",
  EXTERNAL_DEPENDENCY_ERROR: "EXTERNAL_DEPENDENCY_ERROR",
  PERFORMANCE_ERROR: "PERFORMANCE_ERROR",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
} as const;
