import Nav from '@features/Nav';
import '@shared/styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="ko">
        <body>
          <Nav />
          {children}
        </body>
      </html>
    </>
  );
}
