export const assets = {
  buttons: {
    eyeOff: "/assets/buttons/btn_eye_off.svg",
    eyeOn: "/assets/buttons/btn_eye_on.svg",
  },
  icons: {
    x: "/assets/icons/ic_X.svg",
    arrowDown: "/assets/icons/ic_arrow_down.svg",
    arrowLeft: "/assets/icons/ic_arrow_left.svg",
    arrowReturn: "/assets/icons/ic_arrow_return.svg",
    arrowRight: "/assets/icons/ic_arrow_right.svg",
    check: "/assets/icons/ic_check.svg",
    facebook: "/assets/icons/ic_facebook.svg",
    google: "/assets/icons/ic_google.svg",
    heart: "/assets/icons/ic_heart.svg",
    heartActive: "/assets/icons/ic_heart_active.svg",
    heartInactive: "/assets/icons/ic_heart_inactive.svg",
    instagram: "/assets/icons/ic_instagram.svg",
    kakao: "/assets/icons/ic_kakao.svg",
    kebab: "/assets/icons/ic_kebab.svg",
    medal: "/assets/icons/ic_medal.svg",
    plus: "/assets/icons/ic_plus.svg",
    profile: "/assets/icons/ic_profile.svg",
    search: "/assets/icons/ic_search.svg",
    sort: "/assets/icons/ic_sort.svg",
    twitter: "/assets/icons/ic_twitter.svg",
    youtube: "/assets/icons/ic_youtube.svg",
  },
  images: {
    default: "/assets/images/img_default.svg",
    defaultProfile: "/assets/images/img_default_profile.svg",
    homeBottom: "/assets/images/img_home_bottom.svg",
    homeHotItem: "/assets/images/img_home_hot_item.svg",
    homeRegister: "/assets/images/img_home_register.svg",
    homeSearch: "/assets/images/img_home_search.svg",
    homeTop: "/assets/images/img_home_top.svg",
    inquiryEmpty: "/assets/images/img_inquiry_empty.svg",
    replyEmpty: "/assets/images/img_reply_empty.svg",
  },
};
export default assets;
