import Head from "next/head";
import ProductList from "@/components/ProductList";
import Pagination from "@/components/Pagination";
import SearchBar from "@/components/SearchBar";
import useWindowSize from "../hooks/useResize.js";
import * as api from "@/pages/api/products.js";
import { useEffect, useState } from "react";

export async function getServerSideProps() {
  const productsQuery = {
    order: "recent",
    page: 1,
    pageSize: 10,
  };

  const bestProductsQuery = {
    order: "favorite",
    pageSize: 4,
  };

  let items = [];
  let productsTotalCount = 0;
  let bestItems = [];

  try {
    const { list, totalCount } = await api.getProductsAxios(productsQuery);
    items = list;
    productsTotalCount = totalCount;
  } catch (e) {
    console.log(e.message);
  }

  try {
    const { list } = await api.getProductsAxios(bestProductsQuery);
    bestItems = list;
  } catch (e) {
    console.log(e.message);
  }

  return {
    props: {
      items,
      bestItems,
      productsTotalCount,
      productsQuery,
      bestProductsQuery,
    },
  };
}

export default function Home({
  items,
  bestItems,
  productsTotalCount,
  productsQuery,
  bestProductsQuery,
}) {
  const [params, setParams] = useState(productsQuery);
  const [bestParams, setBestParams] = useState(bestProductsQuery);
  const [products, setProducts] = useState(items);
  const [bestProducts, setBestProducts] = useState(bestItems);
  const [totalDataCount, setTotalDataCount] = useState(productsTotalCount);

  const onChange = (name, value) => {
    setParams((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const onObjectChange = (obj) => {
    setParams((prev) => ({
      ...prev,
      ...obj,
    }));
  };

  const onBestChange = (name, value) => {
    setBestParams((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const loadProducts = async (query) => {
    try {
      const { list, totalCount } = await api.getProductsAxios(query);
      setProducts(list);
      setTotalDataCount(totalCount);
    } catch (e) {
      console.log(e.message);
    }
  };

  const loadBestProducts = async (bestParams) => {
    try {
      const { list } = await api.getProductsAxios(bestParams);
      setBestProducts(list);
    } catch (e) {
      console.log(e.message);
    }
  };

  const view = useWindowSize();
  const changeFromNextView = () => {
    switch (view) {
      case "Desktop":
        onChange({ pageSize: 10, page: 1 });
        onBestChange("pageSize", 4);
        break;
      case "isTablet":
        onChange({ pageSize: 6, page: 1 });
        onBestChange("pageSize", 2);
        break;
      case "isMobile":
        onChange({ pageSize: 4, page: 1 });
        onBestChange("pageSize", 1);
        break;
      default:
    }
  };

  useEffect(() => {
    loadProducts(params);
    loadBestProducts(bestParams);
  }, [params]);

  useEffect(() => {
    changeFromNextView();
  }, [view]);

  return (
    <>
      <Head>
        <title>판다마켓</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="products_container">
          <h2>베스트 상품</h2>
          <ProductList items={bestProducts} favorite={true} />
        </div>
        <div className="products_container">
          <SearchBar
            isMobile={view === "isMobile" ? true : false}
            order={params.order}
            onChange={onChange}
          />
          <ProductList items={products} favorite={false} />
        </div>
        <Pagination
          onChange={onChange}
          params={params}
          totalCount={totalDataCount}
        />
      </main>
    </>
  );
}
